version: '3'

services:

  node:
    build:
      context: ./node
    image: anacsz/node:prod
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    image: anacsz/nginx:prod
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /mysql-init/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init/init.sql:/mysql-init/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge